// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S299115_Exam_S21.DataAccess;

namespace S299115_Exam_S21.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20210607053427_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("S299115_Exam_S21.Models.Player", b =>
                {
                    b.Property<int>("ShirtNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(99)
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsThisSeason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerShirtNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.HasKey("ShirtNumber");

                    b.HasIndex("PlayerShirtNumber");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("S299115_Exam_S21.Models.Team", b =>
                {
                    b.Property<string>("TeamName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOfCoach")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ranking")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamName");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("S299115_Exam_S21.Models.Player", b =>
                {
                    b.HasOne("S299115_Exam_S21.Models.Player", null)
                        .WithMany("Players")
                        .HasForeignKey("PlayerShirtNumber");
                });

            modelBuilder.Entity("S299115_Exam_S21.Models.Player", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
